config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pictures#index"
  
  resources :sessions, only: [:create]
  
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_one_attached :filename
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password_confirmation
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :require_signin, only: [:new, :create]
  
  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy!

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:title, :filename)
    end
    
    def require_signin
      if !helpers.signed_in?
        redirect_to '/signin'
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_url
    else
      redirect_to '/signin'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
  
  def signed_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPictures2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if signed_in? %>
      <%= link_to "Sign out", '/signout', data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to "Sign in", '/signin' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :filename, style: "display: block" %>
    <%= form.file_field :filename %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div id="<%= dom_id picture %>">
  <p>
    <strong>Title:</strong>
    <%= picture.title %>
  </p>
  <div>
    <% if picture.filename.attached? %>
      <%= image_tag rails_storage_proxy_path picture.filename %>
    <%  end %>
  </div>

</div>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Show this picture", @picture %> |
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pictures</h1>

<div id="pictures">
  <% @pictures.each do |picture| %>
    <%= render picture %>
    <p>
      <%= link_to "Show this picture", picture %>
    </p>
  <% end %>
</div>

<%= link_to "New picture", new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @picture %>

<div>
  <%= link_to "Edit this picture", edit_picture_path(@picture) %> |
  <%= link_to "Back to pictures", pictures_path %>

  <%= button_to "Destroy this picture", @picture, method: :delete %>
</div>